name: "GitHub cherry pick action"
description: "GitHub action for cherry pick commits from Pull Requests into Release branchs"
inputs:
  token:
    description: "GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)"
    default: ${{ github.token }}
    required: false
  committer:
    description: >
      The committer name and email address in the format `Display Name <email@address.com>`.
      Defaults to the GitHub Actions bot user.
    default: "GitHub <noreply@github.com>"
    required: false
  author:
    description: >
      The author name and email address in the format `Display Name <email@address.com>`.
      Defaults to the user who triggered the workflow run.
    default: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
    required: false
  branch:
    description: "Name of the branch to merge the cherry pick"
    required: true
  labels:
    description: "A comma or newline separated list of labels."
    required: false
  exclude-labels:
    description: "A comma or newline separated list of inherited labels to exclude from the cherry pick PR"
    required: false
  assignees:
    description: "A comma or newline separated list of assignees (GitHub usernames)."
    required: false
  reviewers:
    description: "A comma or newline separated list of reviewers (GitHub usernames) to request a review from."
    required: false
  team-reviewers:
    description: >
      A comma or newline separated list of GitHub teams to request a review from.
      Note that a `repo` scoped Personal Access Token (PAT) may be required.
    required: false
  title-prefix:
    description: >
      A prefix to the inherited title
    required: false
    default: ""
  cherry-pick-repo:
    description: >
      A source repo for the cherry pick PRs
    required: false
    default: ${{ github.repository }}
runs:
  using: node12
  main: dist/index.js
branding:
  icon: 'git-pull-request'
  color: 'orange'
